name: owncloud
version: 8.2.2
vendor: Kyle Fazzari <kyle@canonical.com>
summary: Owncloud
description: Owncloud running on Apache.
icon: icon.svg

services:
  apache:
    start: start_apache
    stop: apachectl stop
  mysql:
    start: start_mysql
    stop: support-files/mysql.server stop
  mdns-publisher:
    start: mdns-publisher owncloud

parts:
  apache:
    plugin: make
    source: src/apache
    stage-packages:
      # Apache dependencies
      - libapr1
      - libaprutil1
      - libpcre3

      # PHP dependencies
      - libxml2
      - libcurl3-gnutls
      - libpng12-0
    build-packages:
      # Apache dependencies
      - libapr1-dev
      - libaprutil1-dev
      - libpcre3-dev

      # PHP dependencies
      - libxml2-dev
      - libcurl4-gnutls-dev
      - libpng12-dev

  mysql:
    plugin: make
    source: src/mysql
    stage-packages:
      - libncurses5
    build-packages:
      - cmake
      - libncurses5-dev

  owncloud:
    plugin: make
    source: src/owncloud

  mdns-publisher:
    # Requires Go 1.3 or later. If you're on trusty, use
    # ppa:ubuntu-lxc/lxd-stable
    plugin: go
    go-packages: [github.com/kyrofa/mdns-publisher]
