name: owncloud
version: 8.2.2ubuntu2
summary: ownCloud
description: ownCloud running on Apache with MySQL. This is currently in beta.
icon: icon.svg

apps:
  # Apache daemon
  apache:
    command: start_apache
    stop-command: apachectl stop
    daemon: simple
    plugs: [listener]

  # MySQL daemon
  mysql:
    command: start_mysql
    stop-command: support-files/mysql.server stop
    daemon: simple
    plugs: [listener]

  # mDNS daemon
  mdns-publisher:
    command: mdns-publisher owncloud
    daemon: simple
    plugs: [listener]

plugs:
  listener:
    interface: old-security
    caps: [network-listener]

parts:
  apache:
    plugin: make
    source: src/apache
    stage-packages:
      # Apache dependencies
      - libapr1
      - libaprutil1
      - libpcre3

      # PHP dependencies
      - libxml2
      - libcurl3
      - libpng12-0
      - libbz2-1.0
      - libmcrypt4
      - libssl1.0.0
    build-packages:
      - wget
      - gcc

      # Apache dependencies
      - libapr1-dev
      - libaprutil1-dev
      - libpcre3-dev

      # PHP dependencies
      - libxml2-dev
      - libcurl4-openssl-dev
      - libpng12-dev
      - libbz2-dev
      - libmcrypt-dev
      - libssl-dev
      - pkg-config
    snap:
      - -manual # No need to include the documentation in the .snap

  mysql:
    plugin: make
    source: src/mysql
    stage-packages:
      - libncurses5
      - libaio1
      - libnuma1
    build-packages:
      - wget
      - g++
      - cmake
      - libncurses5-dev
      - libaio-dev
      - libnuma-dev
    snap:
      # Remove unused binaries that waste space
      - -bin/innochecksum
      - -bin/lz4_decompress
      - -bin/myisam*
      - -bin/mysqladmin
      - -bin/mysqlbinlog
      - -bin/mysql_client_test
      - -bin/mysql_config*
      - -bin/mysqld_multi
      - -bin/mysqldump*
      - -bin/mysqlimport
      - -bin/mysql_install_db
      - -bin/mysql_plugin
      - -bin/mysqlpump
      - -bin/mysql_secure_installation
      - -bin/mysqlshow
      - -bin/mysqlslap
      - -bin/mysql_ssl_rsa_setup
      - -bin/mysqltest
      - -bin/mysql_tzinfo_to_sql
      - -bin/perror
      - -bin/replace
      - -bin/resolveip
      - -bin/resolve_stack_dump
      - -bin/zlib_decompress

  owncloud:
    plugin: make
    source: src/owncloud

  mdns-publisher:
    plugin: go
    go-packages: [github.com/kyrofa/mdns-publisher]
