name: owncloud
version: 8.2.2
vendor: Kyle Fazzari <kyle@canonical.com>
summary: Owncloud
description: Owncloud running on Apache.
icon: icon.svg

services:
  apache:
    start: apachectl start -DFOREGROUND
    stop: apachectl stop

parts:
  apache:
    plugin: make
    source: src
    stage-packages:
      # Apache dependencies
      - libapr1
      - libaprutil1
      - libpcre3

      # PHP dependencies
      - libxml2
    build-packages:
      # Apache dependencies
      - libapr1-dev
      - libaprutil1-dev
      - libpcre3-dev

      # PHP dependencies
      - libxml2-dev
